DELETE FROM Characters;
DELETE FROM Character_Rewards;
DELETE FROM Domain_Rewards;
DELETE FROM Domains;
DELETE FROM Elemental_Interactions;
DELETE FROM Elite_Rewards;
DELETE FROM Elites;
DELETE FROM Enemy_Rewards;
DELETE FROM Enemies;